version: '3.9'

services:
  paymentapi:
    container_name: payment-api
    environment:
      - API_PORT=$API_CONTAINER_PORT
    build:
      context: .
      dockerfile: Dockerfile.api-golang
    ports:
      - $API_HOST_PORT:$API_CONTAINER_PORT
