FROM golang:1.21-alpine AS builder

WORKDIR /app

ADD payment-api/ payment-api/
COPY go.mod ./
COPY go.sum ./
COPY sonar-project.properties ./
COPY Dockerfile.api-golang ./

RUN go build -o paymentapi payment-api/cmd/main.go

FROM alpine:3.14

WORKDIR /app

COPY --from=builder /app/paymentapi .

ENV POSTGRES_DSN=""
ENV API_PORT=""

# Adicionando usuário não-root
RUN adduser -D -u 1001 appuser
USER appuser

CMD ["./paymentapi"]
