// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// Apps is an autogenerated mock type for the apps type
type Apps struct {
	mock.Mock
}

// RegisterRoutes provides a mock function with given fields: routes
func (_m *Apps) RegisterRoutes(routes *gin.RouterGroup) {
	_m.Called(routes)
}

// NewApps creates a new instance of Apps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApps(t interface {
	mock.TestingT
	Cleanup(func())
}) *Apps {
	mock := &Apps{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
